apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-app
  template:
    metadata:
      labels:
        app: edge-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: edge-app
        image: node:18
        workingDir: /app

        command: ["node", "server.js"]

        ports:
          - containerPort: 5000

        volumeMounts:
          - name: app-code
            mountPath: /app

      volumes:
        - name: app-code
          hostPath:
            path: /run/desktop/mnt/host/c/Users/CG/Desktop/aiops-ecommerce/kubernetes/edge
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: NodePort
  selector:
    app: edge-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007